name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: dummy_key

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: pytest -q

      - name: Start FastAPI app
        run: |
          nohup uvicorn server.main:app --host 0.0.0.0 --port 8000 &
          sleep 5

      - name: Smoke test /profile endpoint
        run: |
          curl -X POST http://127.0.0.1:8000/profile \
            -H "Content-Type: application/json" \
            -d '{"company":"テスト企業","preset":"default","statsDataId":""}'
